@ stdcall CallToProtocolHandler(ptr ptr str long)
@ stdcall ConferenceCancelTransfer(ptr long)
@ stdcall ConferenceConnectA(ptr ptr ptr ptr)
@ stdcall ConferenceConnectW(ptr ptr ptr ptr)
@ stdcall ConferenceDisconnect(ptr)
@ stdcall ConferenceGetInfoA(ptr long ptr)
@ stdcall ConferenceGetInfoW(ptr long ptr)
@ stdcall ConferenceLaunchRemote(ptr ptr long)
@ stdcall ConferenceListen(long)
@ stdcall ConferenceRemoveNotify(ptr ptr)
@ stdcall ConferenceSendData(ptr ptr ptr long long)
@ stdcall ConferenceSendFileA(ptr ptr str long)
@ stdcall ConferenceSendFileW(ptr ptr wstr long)
@ stdcall ConferenceSetInfoA(ptr long ptr)
@ stdcall ConferenceSetInfoW(ptr long ptr)
@ stdcall ConferenceSetNotify(ptr ptr ptr)
@ stdcall ConferenceShareWindow(ptr ptr long)
@ stdcall NewMediaPhone(ptr ptr str long)
@ stdcall OpenConfLink(ptr ptr str long)
