#ifndef WATER_FLOWERBOX_RESOURCE_H
#define WATER_FLOWERBOX_RESOURCE_H

#define IDD_FLOWERBOX_CONFIG  100
#define IDC_FLOWERBOX_SHAPE  1001
#define IDC_FLOWERBOX_SPEED  1002
#define IDC_FLOWERBOX_DETAIL 1003

#endif
